"""Week 4 Step 2 — RAG tests.

Real components: ChromaDB (in-process EphemeralClient), PyMuPDF on a real PDF
generated by ReportLab, real PostgreSQL for knowledge_documents.
Substituted via DI: the embedder — a deterministic keyword-axis fake whose
cosine similarities are hand-predictable, so retrieval ranking and the 0.75
threshold are tested exactly (the e5 model itself runs on the deployed stack).
"""

import contextlib
import io
import math
import uuid

import chromadb
import httpx
import pytest
from app.ai.rag.chunking import chunk_pages
from app.core.dependencies import get_chroma_client, get_embedder
from app.main import create_app

ADMIN = {"email": "admin@dgr.gov.ma", "password": "Admin@2026!"}

# Keyword axes: axis 0 = colmatage/fissure, axis 1 = resurfaçage/orniérage,
# axis 2 = béton, axis 3 = filler so no vector is zero.
AXES = {
    "colmatage": 0,
    "fissure": 0,
    "fissures": 0,
    "resurfaçage": 1,
    "orniérage": 1,
    "béton": 2,
}


class FakeEmbedder:
    """Bag-of-keywords projected on 4 axes, L2-normalised — cosine is exact."""

    def _vec(self, text: str) -> list[float]:
        v = [0.0, 0.0, 0.0, 0.2]
        for word in text.lower().replace(",", " ").replace(".", " ").split():
            if word in AXES:
                v[AXES[word]] += 1.0
        norm = math.sqrt(sum(x * x for x in v))
        return [x / norm for x in v]

    def embed_passages(self, texts):
        return [self._vec(t) for t in texts]

    def embed_query(self, text):
        return self._vec(text)


def _make_pdf(pages: list[str]) -> bytes:
    from reportlab.lib.pagesizes import A4
    from reportlab.pdfgen import canvas

    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    for text in pages:
        y = 800
        for line in text.split("\n"):
            c.drawString(50, y, line)
            y -= 16
        c.showPage()
    c.save()
    return buf.getvalue()


PAGE_COLMATAGE = (
    "Norme d'entretien routier.\n"
    "Le colmatage des fissures doit être réalisé par produit bitumineux.\n"
    "Toute fissure de largeur supérieure à 5 mm exige un colmatage préalable."
)
PAGE_RESURFACAGE = (
    "Chapitre resurfaçage.\n"
    "Le resurfaçage est requis lorsque l'orniérage dépasse 15 mm.\n"
    "L'épaisseur minimale de la couche de resurfaçage est de 4 cm."
)


@pytest.fixture
def chroma():
    # EphemeralClient shares one in-process instance: purge the collection so
    # each test starts from a clean corpus (mirrors a dedicated Chroma per env)
    client = chromadb.EphemeralClient()
    with contextlib.suppress(Exception):
        client.delete_collection("normative_corpus")
    yield client


@pytest.fixture
async def client(chroma) -> httpx.AsyncClient:
    app = create_app()
    app.dependency_overrides[get_chroma_client] = lambda: chroma
    app.dependency_overrides[get_embedder] = lambda: FakeEmbedder()
    transport = httpx.ASGITransport(app=app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as c:
        yield c


async def _auth(client) -> dict:
    resp = await client.post("/api/auth/login", json=ADMIN)
    return {"Authorization": f"Bearer {resp.json()['access_token']}"}


async def _ingest(client, headers, title="Norme entretien DGR") -> dict:
    pdf = _make_pdf([PAGE_COLMATAGE, PAGE_RESURFACAGE])
    resp = await client.post(
        "/api/knowledge/documents",
        data={"title": title, "doc_type": "NORME_DGR", "source": "DGR", "version": "2024"},
        files={"file": ("norme.pdf", pdf, "application/pdf")},
        headers=headers,
    )
    assert resp.status_code == 201, resp.text
    return resp.json()


# ---------------- Chunking unit ----------------


def test_chunker_windows_and_pages() -> None:
    """600 + 100 words, 512/50: chunk 0 = 512 words page 1; chunk 1 starts at
    word 462 (overlap 50) -> 238 words spanning pages 1-2."""
    chunks = chunk_pages(["mot " * 600, "fin " * 100], chunk_size=512, overlap=50)
    assert [c.index for c in chunks] == [0, 1]
    assert (chunks[0].page_start, chunks[0].page_end) == (1, 1)
    assert (chunks[1].page_start, chunks[1].page_end) == (1, 2)
    assert len(chunks[1].text.split()) == 238
    with pytest.raises(ValueError):
        chunk_pages(["x"], chunk_size=50, overlap=50)


# ---------------- Ingestion ----------------


async def test_ingest_pdf_extracts_chunks_and_indexes(client, chroma) -> None:
    headers = await _auth(client)
    doc = await _ingest(client, headers)
    assert doc["status"] == "INDEXED"
    assert doc["page_count"] == 2
    assert doc["embedding_count"] >= 1  # short doc -> 1 chunk
    # vectors really are in Chroma
    collection = chroma.get_or_create_collection("normative_corpus")
    stored = collection.get(where={"document_id": doc["id"]})
    assert len(stored["ids"]) == doc["embedding_count"]

    listing = await client.get("/api/knowledge/documents", headers=headers)
    assert any(d["id"] == doc["id"] for d in listing.json())


async def test_ingest_rejects_invalid_inputs(client) -> None:
    headers = await _auth(client)
    bad_type = await client.post(
        "/api/knowledge/documents",
        data={"title": "Doc", "doc_type": "INVALIDE"},
        files={"file": ("x.pdf", b"%PDF-fake", "application/pdf")},
        headers=headers,
    )
    assert bad_type.status_code == 422
    not_pdf = await client.post(
        "/api/knowledge/documents",
        data={"title": "Doc", "doc_type": "ASTM"},
        files={"file": ("x.pdf", b"ceci n'est pas un pdf", "application/pdf")},
        headers=headers,
    )
    assert not_pdf.status_code == 400


# ---------------- Retrieval: ranking + threshold, hand-computed ----------------


async def test_search_ranks_relevant_chunk_first(client) -> None:
    """Query 'colmatage fissure' -> the colmatage page must hit with high
    similarity and carry its citation metadata (title + pages)."""
    headers = await _auth(client)
    doc = await _ingest(client, headers, title="Norme colmatage")

    resp = await client.post(
        "/api/knowledge/search",
        json={"query": "colmatage fissure", "threshold": 0.5},
        headers=headers,
    )
    assert resp.status_code == 200
    hits = resp.json()["hits"]
    assert len(hits) >= 1
    top = hits[0]
    assert "colmatage" in top["text"].lower()
    assert top["title"] == "Norme colmatage"
    assert top["document_id"] == doc["id"]
    assert top["page_start"] >= 1
    assert top["similarity"] > 0.5


async def test_threshold_filters_unrelated_queries(client) -> None:
    """Query 'béton' shares no axis with the corpus: similarity stays low and
    the CDC threshold 0.75 must filter everything out."""
    headers = await _auth(client)
    await _ingest(client, headers)

    resp = await client.post(
        "/api/knowledge/search",
        json={"query": "béton", "threshold": 0.75},
        headers=headers,
    )
    assert resp.status_code == 200
    assert resp.json()["hits"] == []  # nothing citable below threshold


async def test_get_document_and_404(client) -> None:
    headers = await _auth(client)
    doc = await _ingest(client, headers)
    detail = await client.get(f"/api/knowledge/documents/{doc['id']}", headers=headers)
    assert detail.status_code == 200
    missing = await client.get(f"/api/knowledge/documents/{uuid.uuid4()}", headers=headers)
    assert missing.status_code == 404
